shared:
    image: node:12
jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - echo: echo hello
    job1:
        requires: [main]
        steps:
            - echo: sleep 10
    job2:
        requires: [main]
        steps:
            - echo: exit 1
    job3:
        requires: [job1, job2]
        steps:
            - echo: echo hello
    job4:
        requires: [main]
        steps:
            - echo: echo hello
    join:
        requires: [job4, job3]
        steps:
            - echo: echo hello
