shared:
    image: node:12
    sourcePaths: ["!README.md", "!foo.sh"]
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - validate: echo no-op
    publish:
        requires: [main]
        steps:
            - publish: echo no-op
