shared:
    image: node:12
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - validate: echo no-op
    job1:
        requires: [main]
        steps:
            - publish: echo no-op
    job2:
        requires: [main]
        steps:
            - publish: echo no-op
    job3:
        requires: [~job1, ~job2]
        steps:
            - validate: echo no-op
