shared:
    image: node:12
jobs:
    main:
        requires: [~commit, ~pr, ~sd@2:main]
        image: node:12
        steps:
            - echo: echo $SD_JOB_ID
    main-2:
        requires: [~commit, ~pr, ~sd@2:main]
        image: node:12
        steps:
            - echo: |
                echo $SD_JOB_ID
                sleep 5
