shared:
    image: node:12
jobs:
    main:
        requires: [~commit]
        annotations:
            screwdriver.cd/blockedBySameJob: false
            screwdriver.cd/blockedBySameJobWaitTime: 0
        steps:
              - hello: sleep 500
