shared:
    image: node:12
jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - echo: echo hello
    job1:
        requires: [main]
        steps:
            - echo: echo hello
    job2:
        requires: [main]
        steps:
            - echo: echo hello
    job3:
        steps:
            - echo: echo hello
    join:
        requires: [job1, job2, job3]
        steps:
            - echo: echo hello
